# Generated by Django 4.2.7 on 2023-12-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('nom_com', models.CharField(max_length=200, null=True)),
                ('codep_com', models.CharField(max_length=200)),
                ('id_com', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('nom_emp', models.CharField(max_length=200, null=True)),
                ('preno_emp', models.CharField(max_length=200)),
                ('daten_emp', models.CharField(max_length=200)),
                ('adre_emp', models.CharField(max_length=200)),
                ('id_emp', models.AutoField(primary_key=True, serialize=False)),
                ('id_com', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grh.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('nom_ser', models.CharField(max_length=200, null=True)),
                ('id_ser', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Travailler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grh.employee')),
                ('id_ser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grh.service')),
            ],
            options={
                'unique_together': {('id_ser', 'id_emp')},
            },
        ),
    ]
